name: forklift
on:
  schedule:
    # Every Friday
    - cron:  "30 19 * * 5"
jobs:
  forklift:
    runs-on: ubuntu-latest
    steps:
    - name: sync-fork
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.GIT_TOKEN }}
        persist-credentials: true
    - uses: tprasadtp/forklift@master
      with:
        upstream_url: https://github.com/Tecnativa/docker-socket-proxy.git
        upstream_branch: "master"
        branch: "master"
        method: "rebase"
        args: "--no-push"
      env:
        GIT_USER: valarie-ci-bot
        GIT_EMAIL: valarie-ci-bot@users.noreply.github.com
